### ISSUE TITLE
No need to wait after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [cipher812/MPU-6050#1]
Hi, in "MPU6050.cpp" you wait for data with a while-loop after Wire.requestFrom(). You can remove those while loops. There is nothing to wait for.

The Wire.requestFrom() returnes when the I2C transaction has completely finished and all the received data is in a buffer in the Wire library.

**Comment by itzmeabrew** [comment]
Ya thanks for the issue sir,will look into it

**Comment by itzmeabrew** [comment]
fixed
